// <auto-generated />
using Flashcards.WebApp.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Flashcards.WebApp.Migrations
{
    [DbContext(typeof(FlashcardsDbContext))]
    [Migration("20250430114628_AddedConceptTemplates")]
    partial class AddedConceptTemplates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Flashcards.WebApp.Features.ConceptTemplates.ConceptTemplate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_concept_templates");

                    b.ToTable("concept_templates", (string)null);
                });

            modelBuilder.Entity("Flashcards.WebApp.Features.ConceptTemplates.ConceptTemplate", b =>
                {
                    b.OwnsMany("Flashcards.WebApp.Features.ConceptTemplates.ConceptTemplate+Property", "Properties", b1 =>
                        {
                            b1.Property<string>("concept_template_id")
                                .HasColumnType("text")
                                .HasColumnName("concept_template_id");

                            b1.Property<string>("Value")
                                .HasColumnType("text")
                                .HasColumnName("value");

                            b1.HasKey("concept_template_id", "Value")
                                .HasName("pk_concept_template_properties");

                            b1.ToTable("concept_template_properties", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("concept_template_id")
                                .HasConstraintName("fk_concept_template_property_concept_template_id");
                        });

                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
