// <auto-generated />
using Flashcards.WebApp.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Flashcards.WebApp.Infrastructure.Migrations
{
    [DbContext(typeof(FlashcardsDbContext))]
    partial class FlashcardsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Flashcards.WebApp.Features.ConceptTemplates.ConceptTemplate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_concept_templates");

                    b.ToTable("concept_templates", (string)null);
                });

            modelBuilder.Entity("Flashcards.WebApp.Features.ConceptTemplates.ConceptTemplate", b =>
                {
                    b.OwnsMany("Flashcards.WebApp.Features.ConceptTemplates.ConceptTemplate+Property", "Properties", b1 =>
                        {
                            b1.Property<string>("ConceptTemplateId")
                                .HasColumnType("text")
                                .HasColumnName("concept_template_id");

                            b1.Property<string>("Value")
                                .HasColumnType("text")
                                .HasColumnName("Value");

                            b1.HasKey("ConceptTemplateId", "Value")
                                .HasName("pk_concept_template_properties");

                            b1.ToTable("ConceptTemplateProperties", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ConceptTemplateId")
                                .HasConstraintName("fk_concept_template_properties_concept_templates_concept_templat");
                        });

                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
